server:
  port: 8888

# 分组任务配置
chatbot-api:
  launchList: group01 # 启动几组，就配置几组
  group01:
    groupName: ChatGPT AI 问答助手
    groupId:  # 知识星球ID
    cookie:
    openAiKey:  # 自行申请 https://beta.openai.com/overview
    cronExpression: MC8zMCAqICogKiAqID8=  # 执行的频次配置，参考：cron.qqe2.com
    silenced: false
  group02:
    groupName: test
    groupId:  # 知识星球ID
    cookie:  # 知识星球个人cookie信息
    openAiKey:  # 自行申请 https://beta.openai.com/overview
    cronExpression: 0/30 * * * * ? # 执行的频次配置，参考：cron.qqe2.com
    silenced: true
